import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Superheroes SPA - Gian Putallaz',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='es'>
            <body className={inter.className}>
                <div>
                    <Toaster />
                </div>
                <div className='p-4 bg-secondary text-white flex'>
                    <a className='font-jaro text-lg' href='/'>
                        SUPERHEROES SPA
                    </a>
                    <div className='ml-auto flex gap-8 items-center mr-'>
                        <a href='/marvel'>Marvel</a>
                        <a href='/dc'>DC</a>
                    </div>
                </div>
                {children}
            </body>
        </html>
    )
}
